version: "3.7"

services:
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=secret"
    volumes:
      - ./grafana-storage:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus-data:/var/lib/prometheus/data
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.8.1
    volumes:
      - ./elasticsearch-data:/var/lib/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:6.8.1
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  logstash:
    image: docker.elastic.co/logstash/logstash:6.8.1
    ports:
      - "5000:5000"
      - "9600:9600"
    volumes:
      - ./logstash.conf:/etc/logstash/logstash.conf
    command: logstash -f /etc/logstash/logstash.conf
    depends_on:
      - elasticsearch

  zipkin:
    image: openzipkin/zipkin:2.15.0
    ports:
      - "9411:9411"
    environment:
      - STORAGE_TYPE=elasticsearch
      - ES_HOSTS=elasticsearch:9200
    depends_on:
      - elasticsearch

  mongodb:
    image: mongo:3.6.13
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb-data:/data/db

  graylog:
    image: graylog/graylog:3.0.2
    ports:
      # Graylog web interface and API
      - 9000:9000
      # Syslog TCP
      - 514:514
      # Syslog UDP
      - 514:514/udp
      # GELF TCP
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
      - 12202:12202/udp
      - 12203:12203/udp
      - 12204:12204/udp
    environment:
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    volumes:
      - ./graylog-journal:/usr/share/graylog/data/journal
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - elasticsearch
      - mongodb

  # fluentd:
  #   build: fluentd/
  #   ports:
  #     - "24224:24224"
  #     - "24224:24224/udp"
  #   links:
  #     - elasticsearch
  #   depends_on:
  #     - elasticsearch

volumes:
  grafana-storage:
  prometheus-data:
  elasticsearch-data:
  mongodb-data:
  graylog-journal:
