application.name: elk-prometheus-grafana-stack
management.endpoints.web.exposure.include: prometheus
# spring.zipkin.baseUrl: http://localhost:9411/zipkin/
# spring.zipkin.discoveryClientEnabled: false
# spring.zipkin.sender.type: web
logging.level.org.springframework.web: INFO
spring.sleuth.sampler.probability: 1.0
server.error.whitelabel.enabled: false
